version: "3.9"

services:
  web:
    build: .
    command: python /medhub/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/medhub
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=medhub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456qwe

volumes:
  postgres_data: